return {
	folder = {
		default = "",
		open = "",
		empty = "",
		empty_open = "",
		symlink = "",
	},
	diagnostic = {
		error = " ",
		warning = " ",
		hint = "",
		info = " ",
	},
	git = {
		github = "",
		branch_a = "",
		branch_b = "",
		unstaged = "",
		staged = "✓",
		unmerged = "",
		renamed = "",
		deleted_a = "",
		deleted_b = "",
		deleted_c = "✗",
		added_a = "",
		added_b = "",
		modified = "",
		modified_b = "",
		untracked = "?",
		ignored = "◌",
	},
	indicators = {
		check = "",
		check_circle_a = "",
		check_circle_b = "",
		check_box_a = "",
		check_box_b = "",

		pinned = "車",

		times = "",
		times_circle_a = "",
		times_circle_b = "",
		times_box_a = "",
		times_box_b = "",

		question = "",
		question_circle_a = "",
		question_circle_b = "",

		warning = "",
		bug = "",
		hint = "",
		hint_o = "",
		hint_b = "",

		info = "",
		info_circle_a = "",
		info_circle_b = "𥉉",
		info_circle_c = "",
		info_triangle = "",

		plus = "",
		plus_circle_a = "",
		plus_box_a = "",
		plus_box_b = "",

		minus = "",
		minus_circle_a = "",
		minus_circle_b = "",
		minus_circle_c = "",
		minus_box_a = "",
		minus_box_b = "",
	},
	objects = {
		line_v_left = "▎",
		line_v_center = "│",
		line_v_center_thin = "︱",
		triangle_m_right = "",
		triangle_m_down = "",
		triangle_m_up = "",
		triangle_l_right = "",
		triangle_l_left = "",
		angle_l_right = "",
		angle_l_left = "",
		file = "",
		linux = "",
		rocket = "",
		gear = "",
		line_number = "",
		-- = "",
	},

	--#region Plugins icons
	cmp = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "ﴯ",
		Interface = "פּ",
		Module = "穀",
		Property = "",
		Unit = "塞",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},

	telescope = {
		prompt_prefix = " ",
		prompt_prefix_s = "    ",
		selection_caret = " ",
	},

	notify = {
		ERROR = "",
		WARN = "",
		INFO = "",
		DEBUG = "",
		TRACE = "✎",
	},
	trouble = {
		error = "",
		warning = "",
		hint = "",
		information = "",
		other = "﫠",
	},
	wk = {
		breadcrumb = "»", -- symbol used in the command line area that shows your active key combo
		separator = "➜", -- symbol used between a key and it's label
		group = "+", -- symbol prepended to a group
	},
	bufferline = {
		indicator_icon = "▎",
		buffer_close_icon = "",
		modified_icon = "●",
		close_icon = "",
		left_trunc_marker = "",
		right_trunc_marker = "",
	},
	todo_comments = {
		FIX = " ",
		TODO = " ",
		HACK = " ",
		WARN = " ",
		NOTE = " ",
		PERF = " ",
	},
	--#endregion
}
