return {
  modes = {
    normal = "",
    insert = "",
    visual = "",
    replace = "",
  },
  folder = {
    default    = "",
    open       = "",
    empty      = "",
    empty_open = "",
    symlink    = "",
  },
  diagnostic = {
    error   = " ",
    warning = " ",
    hint    = " ",
    info    = " ",
  },
  git = {
    github     = " ",
    branch_a   = " ",
    branch_b   = " ",
    unstaged   = " ",
    staged     = " ",
    unmerged   = " ",
    renamed    = " ",
    deleted_a  = " ",
    deleted_b  = " ",
    deleted_c  = " ",
    added_a    = " ",
    added_b    = " ",
    modified   = " ",
    modified_b = " ",
    untracked  = "? ",
    ignored    = "◌ ",
  },
  indicators = {
    check = " ",
    check_circle_a = " ",
    check_circle_b = " ",
    check_box_a = " ",
    check_box_b = " ",

    pinned = "車",

    times = " ",
    times_circle_a = " ",
    times_circle_b = " ",
    times_box_a = " ",
    times_box_b = " ",

    question = " ",
    question_circle_a = " ",
    question_circle_b = " ",

    warning = " ",
    bug = " ",
    hint = "",
    hint_o = " ",
    hint_b = " ",

    info = " ",
    info_circle_a = " ",
    info_circle_b = "𥉉",
    info_circle_c = " ",
    info_triangle = " ",

    plus = " ",
    plus_circle_a = " ",
    plus_box_a = " ",
    plus_box_b = " ",

    minus = " ",
    minus_circle_a = " ",
    minus_circle_b = " ",
    minus_circle_c = " ",
    minus_box_a = " ",
    minus_box_b = " ",
  },
  objects = {
    line_vert_left = "▎",
    line_vert_center = "│",
    line_vert_center_thin = "︱",
    triangle_m_right = "",
    triangle_m_down = "",
    triangle_m_up = "",
    triangle_l_right = "",
    triangle_l_left = "",
    angle_l_right = "",
    angle_l_left = "",
    angle_lb_right = "❱",
    angle_lb_left = "❰",
    file = " ",
    linux = " ",
    rocket = " ",
    gear = " ",
    line_number = "",
    -- = "",
  },

  --#region Plugins icons
  cmp = {
    Array         = "[]",
    Boolean       = " ",
    Class         = "󰠱 ",
    Color         = " ",
    Constant      = " ",
    Constructor   = " ",
    Copilot       = " ",
    Enum          = " ",
    EnumMember    = " ",
    Event         = "⚡",
    Field         = " ",
    File          = " ",
    Folder        = " ",
    Function      = " ",
    Interface     = " ",
    Key           = "󰀫󰂡",
    Keyword       = " ",
    Method        = " ",
    Module        = " ",
    Namespace     = " ",
    Null          = " ",
    Number        = " ",
    Object        = " ",
    Operator      = " ",
    Package       = " ",
    Property      = " ",
    Reference     = " ",
    Snippet       = " ",
    String        = " ",
    Struct        = " ",
    Text          = " ",
    TypeParameter = "󰰤 ",
    Unit          = " ",
    Value         = "󰀫󰂡",
    Variable      = " ",
  },
  telescope = {
    prompt_prefix = "     ",
    prompt_prefix_s = "    ",
    selection_caret = "▎ ",
  },

  notify = {
    ERROR = "",
    WARN  = "",
    INFO  = "",
    DEBUG = "",
    TRACE = "✎",
  },
  trouble = {
    error       = "󰅗 ",
    warning     = " ",
    hint        = "󰌵 ",
    information = " ",
    other       = " ",
  },
  bufferline = {
    indicator_icon = "▎",
    buffer_close_icon = "󰅖",
    modified_icon = "●",
    close_icon = "",
    left_trunc_marker = "",
    right_trunc_marker = "",
  },
  lazy = {
    cmd        = " ",
    config     = "",
    event      = "",
    ft         = " ",
    init       = " ",
    import     = " ",
    keys       = " ",
    lazy       = "󰒲 ",
    loaded     = "●",
    not_loaded = "○",
    plugin     = " ",
    runtime    = " ",
    source     = " ",
    start      = "",
    task       = "󰸞 ",
    list       = { "●", "➜", "★", "‒" },

  },
  todo_comments = {
    FIX  = " ",
    TODO = " ",
    HACK = " ",
    WARN = " ",
    PERF = "󰾆 ",
    NOTE = " ",
    TEST = " ",
  },
  navic = {
    separator = "  ",
  }
  --#endregion
}
